language: python

python:
  - 3.6

# Notify by email when build results changes
notifications:
  email: change

install:
  - pip install -U tox-travis pytest-cookies pytest cookiecutter

script:
  - py.test tests
